name: arcgis to github

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 15 * * *'

jobs:
  build:
    # spin up virtual machine with latest version of ubuntu
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    # set up python version 3.8 on the ubuntu operating system virtual machine
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # install any require dependencies and run main.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install geopandas
        pip install arcgis
        pip install python-decouple
    - name: Run Python Script
      env:
        ARCGIS_ONLINE_USERNAME: ${{ secrets.ARCGIS_ONLINE_USERNAME }}
        ARCGIS_ONLINE_PASSWORD: ${{ secrets.ARCGIS_ONLINE_PASSWORD }}
      run: |
        python feature_layer_collection_to_gpkg.py
    - name: Commit and push if it changed
      run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add .
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
